### ISSUE TITLE
Stuck in boot loop

### ISSUE THREAD

**Issue by stlnick3** [wfhstudio/EvilCrow-h-RAT#2]
I think the ESP 32 is stuck in a boot loop.

rst:0x10 (RTCWDT_RTC_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
flash read err, 1000
ets_main.c 371
ets Jun8 2016 00:22:57

Flashed with esphome web flasher.

Tried with just the esp32 only and it still won't load

**Comment by stlnick3** [comment]
Used esp flasher 1.4 and it flashed properly.

**Comment by knightr1d3r007** [comment]
@stlnick3 I have a ESP32 Dev kit v1 also in a loop. It happens when connecting to the access point, then ESP32 will reboot. Would please provide a link to the specific flasher you are mentioning please. Thanks in advance.
